# Generated by Django 3.2.14 on 2022-12-01 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateTimeField(blank=True, default=datetime.date(2022, 12, 1))),
                ('counter', models.IntegerField(default=3)),
            ],
        ),
        migrations.AlterField(
            model_name='tekst',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
