# Generated by Django 3.2.14 on 2022-12-01 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221201_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 1, 19, 56, 4, 944627)),
        ),
    ]
