# Generated by Django 3.2.14 on 2022-12-04 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221203_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 4, 21, 9, 24, 951491)),
        ),
        migrations.AlterField(
            model_name='tekst',
            name='opened_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 4), null=True),
        ),
    ]
