# Generated by Django 3.2.14 on 2022-12-04 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_daily_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 4, 21, 11, 47, 883423)),
        ),
        migrations.AlterField(
            model_name='tekst',
            name='opened_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
