# Generated by Django 3.2.14 on 2022-12-06 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221204_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='tekst',
            name='code',
            field=models.CharField(default='LA7XoPgl', max_length=300),
        ),
        migrations.AlterField(
            model_name='daily',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 6, 18, 58, 34, 564064)),
        ),
    ]
