# Generated by Django 3.2.14 on 2022-12-06 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221206_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='tekst',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 6, 19, 12, 3, 210477)),
        ),
        migrations.AlterField(
            model_name='tekst',
            name='code',
            field=models.CharField(default='N1Cwhfkl', max_length=300),
        ),
    ]
