# Generated by Django 3.2.14 on 2022-12-06 18:43

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20221206_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='today',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 6, 19, 43, 4, 364727)),
        ),
        migrations.AlterField(
            model_name='tekst',
            name='code',
            field=models.CharField(default=app.models.unique_rand, max_length=300),
        ),
    ]
